using System.Collections.Generic;
using System.Reflection;
using NixAndEko.Combat;
using NixAndEko.Environment;
using NixAndEko.Level;
using NixAndEko.Player;
using NixAndEko.Util;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.InputSystem;

namespace NixAndEko.EditorTools
{
    /// <summary>
    /// Builds the playable scene from a <see cref="LevelData"/> asset: level geometry, the
    /// archer, and the camera. The default asset is a large multi-zone test level generated by
    /// <see cref="GenerateTestLevel"/>; edit it (or any level) with the Level Editor window.
    /// </summary>
    public static class TestLevelBuilder
    {
        public const string RootName = "-- Nix&Eko Level --";
        const string InputAssetPath = "Assets/InputSystem_Actions.inputactions";
        const string ConfigPath = "Assets/_Game/Data/PlayerConfig.asset";
        public const string LevelPath = "Assets/_Game/Data/TestLevel.asset";

        [MenuItem("Tools/Nix & Eko/Build Test Level", priority = 0)]
        public static void BuildTestLevel()
        {
            LevelData level = AssetDatabase.LoadAssetAtPath<LevelData>(LevelPath);
            if (level == null)
            {
                level = GenerateTestLevel();
                EnsureDataFolder();
                AssetDatabase.CreateAsset(level, LevelPath);
                AssetDatabase.SaveAssets();
                Debug.Log("[Builder] Created " + LevelPath);
            }
            BuildScene(level);
        }

        /// <summary>
        /// Create a clean scene that builds the level from code at launch (a <see cref="LevelLoader"/>
        /// plus a camera), instead of baking every GameObject into the scene. Playing this scene
        /// always reflects the current scripts — no more rebuilding the scene after code changes.
        /// </summary>
        [MenuItem("Tools/Nix & Eko/Setup Runtime Scene (builds on Play)", priority = 2)]
        public static void SetupRuntimeScene()
        {
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;

            LevelData level = AssetDatabase.LoadAssetAtPath<LevelData>(LevelPath);
            if (level == null)
            {
                level = GenerateTestLevel();
                EnsureDataFolder();
                AssetDatabase.CreateAsset(level, LevelPath);
                AssetDatabase.SaveAssets();
            }
            PlayerConfig config = LoadOrCreateConfig();
            var inputAsset = AssetDatabase.LoadAssetAtPath<InputActionAsset>(InputAssetPath);
            EnsureLayer("Ground");

            var scene = EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);

            // 2D game: drop the default directional light, and let LevelLoader finish framing the camera.
            var light = GameObject.Find("Directional Light");
            if (light != null) Object.DestroyImmediate(light);

            var boot = new GameObject("Bootstrap");
            var loader = boot.AddComponent<LevelLoader>();
            loader.level = level;
            loader.playerConfig = config;
            loader.inputActions = inputAsset;

            if (!AssetDatabase.IsValidFolder("Assets/Scenes")) AssetDatabase.CreateFolder("Assets", "Scenes");
            string scenePath = "Assets/Scenes/Game.unity";
            EditorSceneManager.SaveScene(scene, scenePath);

            // Make it the scene that plays from the editor's Play button.
            var scenes = new System.Collections.Generic.List<EditorBuildSettingsScene>(EditorBuildSettings.scenes);
            if (!scenes.Exists(s => s.path == scenePath))
                scenes.Insert(0, new EditorBuildSettingsScene(scenePath, true));
            EditorBuildSettings.scenes = scenes.ToArray();

            Debug.Log("[Builder] Created runtime scene at " + scenePath +
                      ". Press Play — the level is rebuilt from code every launch, so script changes " +
                      "(phantom visuals, tuning, etc.) always take effect without rebuilding the scene.");
        }

        [MenuItem("Tools/Nix & Eko/Regenerate Test Level Asset", priority = 1)]
        public static void RegenerateTestLevelAsset()
        {
            LevelData existing = AssetDatabase.LoadAssetAtPath<LevelData>(LevelPath);
            LevelData generated = GenerateTestLevel();

            if (existing == null)
            {
                EnsureDataFolder();
                AssetDatabase.CreateAsset(generated, LevelPath);
            }
            else
            {
                if (!EditorUtility.DisplayDialog("Regenerate test level?",
                        "This replaces every block in TestLevel.asset with the freshly generated layout. " +
                        "Any hand-made edits to that asset are lost.", "Regenerate", "Cancel"))
                    return;
                Undo.RecordObject(existing, "Regenerate Test Level");
                existing.blocks = generated.blocks;
                existing.playerSpawn = generated.playerSpawn;
                existing.killY = generated.killY;
                EditorUtility.SetDirty(existing);
            }

            AssetDatabase.SaveAssets();
            BuildScene(AssetDatabase.LoadAssetAtPath<LevelData>(LevelPath));
        }

        /// <summary>Instantiate a level plus the player into the open scene, replacing any previous build.</summary>
        public static void BuildScene(LevelData level)
        {
            if (level == null)
            {
                Debug.LogWarning("[Builder] No level asset to build.");
                return;
            }

            int groundLayer = EnsureLayer("Ground");
            PlayerConfig config = LoadOrCreateConfig();
            var inputAsset = AssetDatabase.LoadAssetAtPath<InputActionAsset>(InputAssetPath);
            if (inputAsset == null)
                Debug.LogWarning("[Builder] Input asset not found at " + InputAssetPath +
                                 ". Assign one on the Player's PlayerInputReader.");

            ClearPreviousBuilds();

            var root = new GameObject(RootName);
            root.AddComponent<LevelRoot>();
            Undo.RegisterCreatedObjectUndo(root, "Build Level");

            LevelBuilder.Build(level, root.transform, groundLayer);

            // Faerie-forest backdrop — sky gradient + silhouette trees + drifting fireflies.
            // Scenery's own Start() builds its child assets at runtime, so nothing gets baked in
            // the scene: recolouring the palette and re-running Play is enough to iterate.
            var sceneryGo = new GameObject("Scenery");
            sceneryGo.transform.SetParent(root.transform, false);
            sceneryGo.AddComponent<NixAndEko.Environment.Scenery>();

            Arrow arrow = PlayerFactory.BuildArrowTemplate(root.transform);
            PlayerController player = PlayerFactory.Build(config, inputAsset, groundLayer, arrow,
                                                          level.playerSpawn, root.transform, level.killY);

            var hudGo = new GameObject("DebugHUD");
            hudGo.transform.SetParent(root.transform, false);
            var hud = hudGo.AddComponent<DebugHud>();
            hud.player = player;
            hud.health = player.GetComponent<Health>();
            hud.bow = player.GetComponentInChildren<Bow>();

            var mapGo = new GameObject("MapDisplay");
            mapGo.transform.SetParent(root.transform, false);
            var map = mapGo.AddComponent<NixAndEko.Environment.MapDisplay>();
            map.level = level;
            map.player = player.transform;
            map.input = player.GetComponent<NixAndEko.Player.PlayerInputReader>();
            var ekoT = root.transform.Find("Eko");
            if (ekoT != null) map.secondary = ekoT;

            ConfigureCamera(level, player);

            Selection.activeGameObject = root;
            UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(
                UnityEngine.SceneManagement.SceneManager.GetActiveScene());
            Debug.Log("[Builder] Built '" + level.name + "' (" + level.blocks.Count + " blocks). Press Play.\n" +
                      "Keyboard: A/D move, Space jump, C crouch (C+Space drops through white platforms). " +
                      "Mouse aims. LMB = Nix Bow (fire / walk over your arrow to reclaim it), RMB = Nix Melee, Q = Eko.\n" +
                      "Gamepad (PS5 labels): left stick or d-pad move, X jump, Circle crouch. Right stick aims. " +
                      "R2 = Nix Bow, R1 = Nix Melee (3-hit combo with an arrow, roll without), L1 = Eko.\n" +
                      "L1 plants Eko where Nix stands and hands you control of it — Nix ghosts (crouched, " +
                      "translucent, intangible, frozen) while you drive Eko. Aim Eko with the right stick / " +
                      "mouse; the straight blue line previews the shot (Eko's arrows ignore gravity). " +
                      "L1 again plants Eko where it stands with its aim kept — control returns to Nix and " +
                      "Eko freezes so an air shot lines up cleanly. From Nix, L1 fires the planted shot. " +
                      "R2 while possessing is the shortcut: plant + fire in one press. Walk Eko onto Nix's " +
                      "downed arrow to grab it — it's handed back on the return. When Nix is empty, R2 " +
                      "sends Eko to fetch the arrow instead (a planted phantom vanishes first). Cling to " +
                      "walls to slide.");
        }

        /// <summary>Root names used by earlier versions, cleaned up so rebuilds never stack up.</summary>
        static readonly string[] LegacyRootNames =
        {
            "— Nix&Eko Test Level —",
            "-- Nix&Eko Test Level --",
        };

        /// <summary>Remove any previous build: marked roots first, then known legacy names.</summary>
        static void ClearPreviousBuilds()
        {
            foreach (var marker in Object.FindObjectsByType<LevelRoot>(
                         FindObjectsInactive.Include, FindObjectsSortMode.None))
                if (marker != null) Object.DestroyImmediate(marker.gameObject);

            var byName = new List<string>(LegacyRootNames) { RootName };
            foreach (string n in byName)
            {
                GameObject go;
                while ((go = GameObject.Find(n)) != null)
                    Object.DestroyImmediate(go);
            }
        }

        [MenuItem("Tools/Nix & Eko/Create Player Config", priority = 20)]
        public static void CreatePlayerConfigMenu() => LoadOrCreateConfig();

        // ============================================================ big test level (as data)

        /// <summary>
        /// A large multi-zone playground: a benchmarking zone (unit-block distance ruler, height
        /// ruler, gap-distance ladder) to tune feel, a long surface run, a wall-slide descent, a
        /// vertical shaft climbed with recoil pogo shots, a hazard gauntlet, a switch-and-gate
        /// puzzle and a breakable-wall vault. Roughly 300 x 65 units.
        /// </summary>
        public static LevelData GenerateTestLevel()
        {
            var d = ScriptableObject.CreateInstance<LevelData>();
            d.name = "TestLevel";
            d.killY = -40f;

            var b = new List<LevelBlock>();

            void Block(BlockType t, float x, float y, float w, float h)
            {
                b.Add(new LevelBlock
                {
                    type = t,
                    position = new Vector2(x, y),
                    size = new Vector2(w, h),
                });
            }

            // ---------------- Zone 0: benchmarking ground (west of everything else) ----------------
            // Built for tuning feel rather than exploration: a run of literal 1×1 unit blocks to
            // gauge distance by eye (or by counting), a shaft with a tick mark at every integer
            // height to read a jump's peak against, and a line of landing pads with gaps stepping
            // 1 through 10 units to see exactly how far a jump carries horizontally. Cross-check
            // against PlayerConfig's derived MaxJumpHeight / MaxAirTime / MaxJumpDistance — or lock
            // one of them and dial the physics in to land on an exact number here (see
            // PlayerConfigEditor's lock toggles).
            const float benchFloorY = -5.5f;   // top surface at -5, matching Zone 1's plateau

            Block(BlockType.Ground, -224f, 8f, 2f, 44f);   // far-west world wall

            // -- distance ruler: standard 1x1 unit blocks, laid one after another --
            for (int i = 0; i < 28; i++)
                Block(BlockType.Ground, -222f + i, benchFloorY, 1f, 1f);

            Block(BlockType.Checkpoint, -220f, -4f, 1f, 2f);
            d.playerSpawn = new Vector2(-220f, -2f);

            // -- height ruler: a shaft with a tick mark at every integer height above the floor --
            Block(BlockType.Ground, -195f, 8f, 2f, 44f);           // shaft left wall
            Block(BlockType.Ground, -181f, 8f, 2f, 44f);           // shaft right wall
            Block(BlockType.Ground, -188f, benchFloorY, 12f, 1f);  // shaft floor, same top as the ruler
            for (int h = 1; h <= 10; h++)
                Block(BlockType.Ground, -193f, -5f + h - 0.15f, 1f, 0.3f); // tick mark, top = floor + h

            // -- distance test: landing pads with gaps stepping 1 through 10 units --
            float benchX = -177f;
            Block(BlockType.Ground, benchX + 1f, -6f, 2f, 2f);     // first pad
            benchX += 2f;
            for (int gap = 1; gap <= 10; gap++)
            {
                benchX += gap;                                     // the gap itself
                Block(BlockType.Ground, benchX + 1f, -6f, 2f, 2f); // pad after a `gap`-unit gap
                benchX += 2f;
            }
            float connectorWidth = -76f - benchX;                  // bridge back to Zone 1's plateau
            Block(BlockType.Ground, benchX + connectorWidth * 0.5f, -6f, connectorWidth, 2f);

            // ---------------- Zone 1: surface run (west) ----------------
            Block(BlockType.Ground, -56f, -6f, 40f, 2f);        // start plateau
            Block(BlockType.Ground, -30f, -8f, 14f, 2f);        // step down
            Block(BlockType.Hazard, -30f, -6.6f, 10f, 0.6f);    // spike strip to hop
            Block(BlockType.Ground, -16f, -6f, 12f, 2f);
            Block(BlockType.OneWay, -46f, -1f, 6f, 0.4f);       // hop up through, crouch-drop back
            Block(BlockType.OneWay, -38f, 3f, 6f, 0.4f);
            Block(BlockType.Ground, -48f, 7f, 10f, 1f);         // upper shelf
            Block(BlockType.Checkpoint, -56f, -4.5f, 1f, 2f);
            Block(BlockType.EnemyWalker, -62f, -4.5f, 0.9f, 1f);   // paces the start plateau
            Block(BlockType.EnemySlammer, -16f, -4.5f, 1f, 0.9f);  // pounds the step-down ledge
            Block(BlockType.EnemyWalker, -92f, -4.5f, 0.9f, 1f);   // the long connector run
            Block(BlockType.EnemySlammer, -46f, -4.5f, 1f, 0.9f);  // guards the plateau
            Block(BlockType.EnemyWalker, -48f, 8f, 0.9f, 1f);      // patrols the upper shelf

            // ---------------- Zone 2: wall-slide descent ----------------
            Block(BlockType.Ground, -8f, 4f, 2f, 26f);          // tall left wall
            Block(BlockType.Ground, -2f, 6f, 2f, 22f);          // tall right wall
            Block(BlockType.Ground, -5f, -6f, 4f, 2f);          // landing floor
            Block(BlockType.Hazard, -5f, -4.6f, 2f, 0.6f);      // punishes a straight drop
            b.Add(new LevelBlock
            {
                type = BlockType.MovingPlatform,
                position = new Vector2(-5f, 10f),
                size = new Vector2(3f, 0.5f),
                patrolOffset = new Vector2(0f, -8f),
                speed = 2.5f,
            });

            // ---------------- Zone 3: recoil pogo shaft (vertical) ----------------
            Block(BlockType.Ground, 4f, 6f, 2f, 34f);
            Block(BlockType.Ground, 16f, 6f, 2f, 34f);
            Block(BlockType.Ground, 10f, -6f, 10f, 2f);         // shaft floor
            Block(BlockType.Ground, 7f, 0f, 4f, 1f);            // staggered ledges to pogo between
            Block(BlockType.Ground, 13f, 6f, 4f, 1f);
            Block(BlockType.Ground, 7f, 12f, 4f, 1f);
            Block(BlockType.Ground, 13f, 18f, 4f, 1f);
            Block(BlockType.Checkpoint, 10f, -4.5f, 1f, 2f);
            Block(BlockType.Ground, 10f, 23f, 14f, 1f);         // shaft top

            // ---------------- Zone 4: hazard gauntlet (east, high) ----------------
            Block(BlockType.Ground, 26f, 16f, 14f, 1f);
            Block(BlockType.Hazard, 24f, 17f, 3f, 0.6f);
            Block(BlockType.Hazard, 30f, 17f, 3f, 0.6f);
            b.Add(new LevelBlock
            {
                type = BlockType.MovingPlatform,
                position = new Vector2(38f, 16f),
                size = new Vector2(3f, 0.5f),
                patrolOffset = new Vector2(9f, 0f),
                speed = 3.5f,
            });
            Block(BlockType.Ground, 52f, 16f, 12f, 1f);
            Block(BlockType.Checkpoint, 52f, 17.5f, 1f, 2f);

            // ---------------- Zone 5: switch and gate puzzle ----------------
            b.Add(new LevelBlock
            {
                type = BlockType.Gate,
                position = new Vector2(60f, 12f),
                size = new Vector2(1.5f, 8f),
                linkId = 1,
                openOffset = new Vector2(0f, 8.5f),
            });
            b.Add(new LevelBlock
            {
                type = BlockType.TargetSwitch,
                position = new Vector2(46f, 22f),
                size = new Vector2(1f, 1f),
                linkId = 1,
            });
            Block(BlockType.Ground, 66f, 8f, 12f, 1f);          // reward ledge past the gate
            Block(BlockType.Ground, 74f, 12f, 2f, 30f);         // east boundary

            // ---------------- Zone 6: breakable vault (below the gauntlet) ----------------
            Block(BlockType.Ground, 34f, 2f, 24f, 1f);
            Block(BlockType.Ground, 24f, 6f, 2f, 9f);
            b.Add(new LevelBlock
            {
                type = BlockType.BreakableWall,
                position = new Vector2(44f, 5f),
                size = new Vector2(1.5f, 5f),
                minCharge = 0.6f,
            });
            Block(BlockType.Ground, 52f, 2f, 14f, 1f);
            Block(BlockType.Checkpoint, 50f, 3.5f, 1f, 2f);
            Block(BlockType.Hazard, 34f, 2.8f, 6f, 0.6f);

            // ---------------- Enemies scattered through the later zones ----------------
            Block(BlockType.EnemyWalker, 12f, -4.5f, 0.9f, 1f);    // recoil-shaft floor
            Block(BlockType.EnemySlammer, 13f, 6.9f, 1f, 0.9f);    // a shaft pogo ledge
            Block(BlockType.EnemyWalker, 28f, 17f, 0.9f, 1f);      // hazard gauntlet
            Block(BlockType.EnemySlammer, 52f, 16.9f, 1f, 0.9f);   // gauntlet far platform
            Block(BlockType.EnemyWalker, 30f, 3f, 0.9f, 1f);       // breakable vault floor
            Block(BlockType.EnemyWalker, 55f, 3f, 0.9f, 1f);       // east vault floor
            Block(BlockType.EnemySlammer, 68f, 8.9f, 1f, 0.9f);    // reward ledge past the gate

            d.blocks = b;
            return d;
        }

        // ============================================================ helpers

        static void ConfigureCamera(LevelData level, PlayerController player = null)
        {
            var cam = Camera.main;
            if (cam == null) return;

            cam.orthographic = true;
            cam.orthographicSize = 10f;
            cam.backgroundColor = Palette.Black;
            cam.transform.position = new Vector3(level.playerSpawn.x, level.playerSpawn.y + 3f, -10f);

            var type = System.Type.GetType("UnityEngine.U2D.PixelPerfectCamera, Unity.2D.PixelPerfect.Runtime")
                       ?? System.Type.GetType("UnityEngine.U2D.PixelPerfectCamera, Unity.RenderPipelines.Universal.Runtime");
            if (type != null && cam.GetComponent(type) == null)
            {
                var ppc = cam.gameObject.AddComponent(type);
                TrySet(ppc, "assetsPPU", SpriteFactory.PPU);
                TrySet(ppc, "refResolutionX", 384);
                TrySet(ppc, "refResolutionY", 216);
                TrySet(ppc, "upscaleRT", true);
                TrySet(ppc, "pixelSnapping", true);
            }

            // The level is far bigger than one screen now, so the camera follows the archer.
            var follow = cam.GetComponent<CameraFollow>();
            if (follow == null) follow = cam.gameObject.AddComponent<CameraFollow>();
            // Eko is a second PlayerController sharing the scene now, so this has to be explicit —
            // CameraFollow's own "find any PlayerController" fallback can no longer tell them apart.
            if (player != null) follow.target = player.transform;
        }

        static void TrySet(Object target, string field, object value)
        {
            var t = target.GetType();
            var p = t.GetProperty(field, BindingFlags.Public | BindingFlags.Instance);
            if (p != null && p.CanWrite) { p.SetValue(target, value); return; }
            var f = t.GetField(field, BindingFlags.Public | BindingFlags.Instance);
            if (f != null) f.SetValue(target, value);
        }

        static void EnsureDataFolder()
        {
            if (AssetDatabase.IsValidFolder("Assets/_Game/Data")) return;
            if (!AssetDatabase.IsValidFolder("Assets/_Game")) AssetDatabase.CreateFolder("Assets", "_Game");
            AssetDatabase.CreateFolder("Assets/_Game", "Data");
        }

        public static PlayerConfig LoadOrCreateConfig()
        {
            var cfg = AssetDatabase.LoadAssetAtPath<PlayerConfig>(ConfigPath);
            if (cfg != null) return cfg;

            EnsureDataFolder();
            cfg = ScriptableObject.CreateInstance<PlayerConfig>();
            AssetDatabase.CreateAsset(cfg, ConfigPath);
            AssetDatabase.SaveAssets();
            Debug.Log("[Builder] Created " + ConfigPath);
            return cfg;
        }

        /// <summary>Ensure a user layer exists; return its index (falls back to Default=0).</summary>
        public static int EnsureLayer(string layerName)
        {
            int existing = LayerMask.NameToLayer(layerName);
            if (existing >= 0) return existing;

            var asset = AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/TagManager.asset");
            if (asset.Length == 0) return 0;

            var tagManager = new SerializedObject(asset[0]);
            var layers = tagManager.FindProperty("layers");

            for (int i = 8; i < layers.arraySize; i++) // 0-7 are Unity built-ins
            {
                var sp = layers.GetArrayElementAtIndex(i);
                if (string.IsNullOrEmpty(sp.stringValue))
                {
                    sp.stringValue = layerName;
                    tagManager.ApplyModifiedProperties();
                    AssetDatabase.SaveAssets();
                    Debug.Log("[Builder] Created layer '" + layerName + "' at index " + i + ".");
                    return i;
                }
            }

            Debug.LogWarning("[Builder] No free layer slots; using Default.");
            return 0;
        }
    }
}
