using System.Collections.Generic;
using System.Reflection;
using NixAndEko.Combat;
using NixAndEko.Environment;
using NixAndEko.Level;
using NixAndEko.Player;
using NixAndEko.Util;
using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;

namespace NixAndEko.EditorTools
{
    /// <summary>
    /// Builds the playable scene from a <see cref="LevelData"/> asset: level geometry, the
    /// archer, and the camera. The default asset is a large multi-zone test level generated by
    /// <see cref="GenerateTestLevel"/>; edit it (or any level) with the Level Editor window.
    /// </summary>
    public static class TestLevelBuilder
    {
        public const string RootName = "-- Nix&Eko Level --";
        const string InputAssetPath = "Assets/InputSystem_Actions.inputactions";
        const string ConfigPath = "Assets/_Game/Data/PlayerConfig.asset";
        public const string LevelPath = "Assets/_Game/Data/TestLevel.asset";

        [MenuItem("Tools/Nix & Eko/Build Test Level", priority = 0)]
        public static void BuildTestLevel()
        {
            LevelData level = AssetDatabase.LoadAssetAtPath<LevelData>(LevelPath);
            if (level == null)
            {
                level = GenerateTestLevel();
                EnsureDataFolder();
                AssetDatabase.CreateAsset(level, LevelPath);
                AssetDatabase.SaveAssets();
                Debug.Log("[Builder] Created " + LevelPath);
            }
            BuildScene(level);
        }

        [MenuItem("Tools/Nix & Eko/Regenerate Test Level Asset", priority = 1)]
        public static void RegenerateTestLevelAsset()
        {
            LevelData existing = AssetDatabase.LoadAssetAtPath<LevelData>(LevelPath);
            LevelData generated = GenerateTestLevel();

            if (existing == null)
            {
                EnsureDataFolder();
                AssetDatabase.CreateAsset(generated, LevelPath);
            }
            else
            {
                if (!EditorUtility.DisplayDialog("Regenerate test level?",
                        "This replaces every block in TestLevel.asset with the freshly generated layout. " +
                        "Any hand-made edits to that asset are lost.", "Regenerate", "Cancel"))
                    return;
                Undo.RecordObject(existing, "Regenerate Test Level");
                existing.blocks = generated.blocks;
                existing.playerSpawn = generated.playerSpawn;
                existing.killY = generated.killY;
                EditorUtility.SetDirty(existing);
            }

            AssetDatabase.SaveAssets();
            BuildScene(AssetDatabase.LoadAssetAtPath<LevelData>(LevelPath));
        }

        /// <summary>Instantiate a level plus the player into the open scene, replacing any previous build.</summary>
        public static void BuildScene(LevelData level)
        {
            if (level == null)
            {
                Debug.LogWarning("[Builder] No level asset to build.");
                return;
            }

            int groundLayer = EnsureLayer("Ground");
            PlayerConfig config = LoadOrCreateConfig();
            var inputAsset = AssetDatabase.LoadAssetAtPath<InputActionAsset>(InputAssetPath);
            if (inputAsset == null)
                Debug.LogWarning("[Builder] Input asset not found at " + InputAssetPath +
                                 ". Assign one on the Player's PlayerInputReader.");

            var existing = GameObject.Find(RootName);
            if (existing != null) Object.DestroyImmediate(existing);

            var root = new GameObject(RootName);
            Undo.RegisterCreatedObjectUndo(root, "Build Level");

            LevelBuilder.Build(level, root.transform, groundLayer);

            Arrow arrow = PlayerFactory.BuildArrowTemplate(root.transform);
            PlayerController player = PlayerFactory.Build(config, inputAsset, groundLayer, arrow,
                                                          level.playerSpawn, root.transform, level.killY);

            var hudGo = new GameObject("DebugHUD");
            hudGo.transform.SetParent(root.transform, false);
            var hud = hudGo.AddComponent<DebugHud>();
            hud.player = player;
            hud.health = player.GetComponent<Health>();
            hud.bow = player.GetComponentInChildren<Bow>();

            ConfigureCamera(level);

            Selection.activeGameObject = root;
            UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(
                UnityEngine.SceneManagement.SceneManager.GetActiveScene());
            Debug.Log("[Builder] Built '" + level.name + "' (" + level.blocks.Count + " blocks). Press Play. " +
                      "A/D move, Space jump (hold = higher), Ctrl crouch (Ctrl+Space drops through white platforms), " +
                      "cling to walls to slide. Hold LMB to draw, drag from the circle to aim in 8 directions, " +
                      "release to fire - mid-air shots recoil you the opposite way.");
        }

        [MenuItem("Tools/Nix & Eko/Create Player Config", priority = 20)]
        public static void CreatePlayerConfigMenu() => LoadOrCreateConfig();

        // ============================================================ big test level (as data)

        /// <summary>
        /// A large multi-zone playground: a long surface run, a wall-slide descent, a vertical
        /// shaft climbed with recoil pogo shots, a hazard gauntlet, a switch-and-gate puzzle and
        /// a breakable-wall vault. Roughly 150 x 65 units.
        /// </summary>
        public static LevelData GenerateTestLevel()
        {
            var d = ScriptableObject.CreateInstance<LevelData>();
            d.name = "TestLevel";
            d.playerSpawn = new Vector2(-56f, -2f);
            d.killY = -40f;

            var b = new List<LevelBlock>();

            void Block(BlockType t, float x, float y, float w, float h)
            {
                b.Add(new LevelBlock
                {
                    type = t,
                    position = new Vector2(x, y),
                    size = new Vector2(w, h),
                });
            }

            // ---------------- Zone 1: surface run (west) ----------------
            Block(BlockType.Ground, -56f, -6f, 40f, 2f);        // start plateau
            Block(BlockType.Ground, -76f, 2f, 2f, 18f);         // west boundary wall
            Block(BlockType.Ground, -30f, -8f, 14f, 2f);        // step down
            Block(BlockType.Hazard, -30f, -6.6f, 10f, 0.6f);    // spike strip to hop
            Block(BlockType.Ground, -16f, -6f, 12f, 2f);
            Block(BlockType.OneWay, -46f, -1f, 6f, 0.4f);       // hop up through, crouch-drop back
            Block(BlockType.OneWay, -38f, 3f, 6f, 0.4f);
            Block(BlockType.Ground, -48f, 7f, 10f, 1f);         // upper shelf
            Block(BlockType.Checkpoint, -56f, -4.5f, 1f, 2f);

            // ---------------- Zone 2: wall-slide descent ----------------
            Block(BlockType.Ground, -8f, 4f, 2f, 26f);          // tall left wall
            Block(BlockType.Ground, -2f, 6f, 2f, 22f);          // tall right wall
            Block(BlockType.Ground, -5f, -6f, 4f, 2f);          // landing floor
            Block(BlockType.Hazard, -5f, -4.6f, 2f, 0.6f);      // punishes a straight drop
            b.Add(new LevelBlock
            {
                type = BlockType.MovingPlatform,
                position = new Vector2(-5f, 10f),
                size = new Vector2(3f, 0.5f),
                patrolOffset = new Vector2(0f, -8f),
                speed = 2.5f,
            });

            // ---------------- Zone 3: recoil pogo shaft (vertical) ----------------
            Block(BlockType.Ground, 4f, 6f, 2f, 34f);
            Block(BlockType.Ground, 16f, 6f, 2f, 34f);
            Block(BlockType.Ground, 10f, -6f, 10f, 2f);         // shaft floor
            Block(BlockType.Ground, 7f, 0f, 4f, 1f);            // staggered ledges to pogo between
            Block(BlockType.Ground, 13f, 6f, 4f, 1f);
            Block(BlockType.Ground, 7f, 12f, 4f, 1f);
            Block(BlockType.Ground, 13f, 18f, 4f, 1f);
            Block(BlockType.Checkpoint, 10f, -4.5f, 1f, 2f);
            Block(BlockType.Ground, 10f, 23f, 14f, 1f);         // shaft top

            // ---------------- Zone 4: hazard gauntlet (east, high) ----------------
            Block(BlockType.Ground, 26f, 16f, 14f, 1f);
            Block(BlockType.Hazard, 24f, 17f, 3f, 0.6f);
            Block(BlockType.Hazard, 30f, 17f, 3f, 0.6f);
            b.Add(new LevelBlock
            {
                type = BlockType.MovingPlatform,
                position = new Vector2(38f, 16f),
                size = new Vector2(3f, 0.5f),
                patrolOffset = new Vector2(9f, 0f),
                speed = 3.5f,
            });
            Block(BlockType.Ground, 52f, 16f, 12f, 1f);
            Block(BlockType.Checkpoint, 52f, 17.5f, 1f, 2f);

            // ---------------- Zone 5: switch and gate puzzle ----------------
            b.Add(new LevelBlock
            {
                type = BlockType.Gate,
                position = new Vector2(60f, 12f),
                size = new Vector2(1.5f, 8f),
                linkId = 1,
                openOffset = new Vector2(0f, 8.5f),
            });
            b.Add(new LevelBlock
            {
                type = BlockType.TargetSwitch,
                position = new Vector2(46f, 22f),
                size = new Vector2(1f, 1f),
                linkId = 1,
            });
            Block(BlockType.Ground, 66f, 8f, 12f, 1f);          // reward ledge past the gate
            Block(BlockType.Ground, 74f, 12f, 2f, 30f);         // east boundary

            // ---------------- Zone 6: breakable vault (below the gauntlet) ----------------
            Block(BlockType.Ground, 34f, 2f, 24f, 1f);
            Block(BlockType.Ground, 24f, 6f, 2f, 9f);
            b.Add(new LevelBlock
            {
                type = BlockType.BreakableWall,
                position = new Vector2(44f, 5f),
                size = new Vector2(1.5f, 5f),
                minCharge = 0.6f,
            });
            Block(BlockType.Ground, 52f, 2f, 14f, 1f);
            Block(BlockType.Checkpoint, 50f, 3.5f, 1f, 2f);
            Block(BlockType.Hazard, 34f, 2.8f, 6f, 0.6f);

            d.blocks = b;
            return d;
        }

        // ============================================================ helpers

        static void ConfigureCamera(LevelData level)
        {
            var cam = Camera.main;
            if (cam == null) return;

            cam.orthographic = true;
            cam.orthographicSize = 10f;
            cam.backgroundColor = Palette.Black;
            cam.transform.position = new Vector3(level.playerSpawn.x, level.playerSpawn.y + 3f, -10f);

            var type = System.Type.GetType("UnityEngine.U2D.PixelPerfectCamera, Unity.2D.PixelPerfect.Runtime")
                       ?? System.Type.GetType("UnityEngine.U2D.PixelPerfectCamera, Unity.RenderPipelines.Universal.Runtime");
            if (type != null && cam.GetComponent(type) == null)
            {
                var ppc = cam.gameObject.AddComponent(type);
                TrySet(ppc, "assetsPPU", SpriteFactory.PPU);
                TrySet(ppc, "refResolutionX", 384);
                TrySet(ppc, "refResolutionY", 216);
                TrySet(ppc, "upscaleRT", true);
                TrySet(ppc, "pixelSnapping", true);
            }

            // The level is far bigger than one screen now, so the camera follows the archer.
            if (cam.GetComponent<CameraFollow>() == null)
                cam.gameObject.AddComponent<CameraFollow>();
        }

        static void TrySet(Object target, string field, object value)
        {
            var t = target.GetType();
            var p = t.GetProperty(field, BindingFlags.Public | BindingFlags.Instance);
            if (p != null && p.CanWrite) { p.SetValue(target, value); return; }
            var f = t.GetField(field, BindingFlags.Public | BindingFlags.Instance);
            if (f != null) f.SetValue(target, value);
        }

        static void EnsureDataFolder()
        {
            if (AssetDatabase.IsValidFolder("Assets/_Game/Data")) return;
            if (!AssetDatabase.IsValidFolder("Assets/_Game")) AssetDatabase.CreateFolder("Assets", "_Game");
            AssetDatabase.CreateFolder("Assets/_Game", "Data");
        }

        public static PlayerConfig LoadOrCreateConfig()
        {
            var cfg = AssetDatabase.LoadAssetAtPath<PlayerConfig>(ConfigPath);
            if (cfg != null) return cfg;

            EnsureDataFolder();
            cfg = ScriptableObject.CreateInstance<PlayerConfig>();
            AssetDatabase.CreateAsset(cfg, ConfigPath);
            AssetDatabase.SaveAssets();
            Debug.Log("[Builder] Created " + ConfigPath);
            return cfg;
        }

        /// <summary>Ensure a user layer exists; return its index (falls back to Default=0).</summary>
        public static int EnsureLayer(string layerName)
        {
            int existing = LayerMask.NameToLayer(layerName);
            if (existing >= 0) return existing;

            var asset = AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/TagManager.asset");
            if (asset.Length == 0) return 0;

            var tagManager = new SerializedObject(asset[0]);
            var layers = tagManager.FindProperty("layers");

            for (int i = 8; i < layers.arraySize; i++) // 0-7 are Unity built-ins
            {
                var sp = layers.GetArrayElementAtIndex(i);
                if (string.IsNullOrEmpty(sp.stringValue))
                {
                    sp.stringValue = layerName;
                    tagManager.ApplyModifiedProperties();
                    AssetDatabase.SaveAssets();
                    Debug.Log("[Builder] Created layer '" + layerName + "' at index " + i + ".");
                    return i;
                }
            }

            Debug.LogWarning("[Builder] No free layer slots; using Default.");
            return 0;
        }
    }
}
